version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MySamApp"
s3_bucket = "my-sam-deployment-bucket"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
